---
# Shell installation and configuration
- name: Configure Shell Environment
  block:
    # Fish Shell Installation
    - name: Remove existing repository files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/apt/sources.list.d/fish-shell.list
        - /etc/apt/sources.list.d/fish-shell-ubuntu-release-3-noble.list
        - /etc/apt/keyrings/fish-shell.gpg
        - /etc/apt/keyrings/fish-shell.asc
        - /etc/apt/trusted.gpg.d/fish-shell.gpg
        - /etc/apt/sources.list.d/fish-shell-ppa.list

    - name: Manage fish shell repository
      block:
        - name: Remove fish repository if installed
          ansible.builtin.apt_repository:
            repo: "ppa:fish-shell/release-3"
            state: absent

        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: true

        - name: Add fish shell repository
          ansible.builtin.apt_repository:
            repo: "ppa:fish-shell/release-3"
            state: present
            update_cache: true

    - name: Install and configure fish
      block:
        - name: Install fish shell
          ansible.builtin.apt:
            name: fish
            state: present
            update_cache: true

        - name: Change default shell to fish for user
          ansible.builtin.user:
            name: "{{ ansible_user }}"
            shell: /usr/bin/fish

    # Fish Configuration
    - name: Configure fish
      block:
        - name: Create fish config directory
          become: false
          ansible.builtin.file:
            path: "/home/{{ ansible_user }}/.config/fish"
            state: directory
            mode: "0755"

        - name: Add Rust to fish config
          become: false
          ansible.builtin.blockinfile:
            path: "/home/{{ ansible_user }}/.config/fish/config.fish"
            create: true
            mode: "0644"
            marker: "# {mark} RUST CONFIGURATION"
            block: |
              # Add Cargo bin directory to PATH
              if test -d $HOME/.cargo/bin
                  fish_add_path $HOME/.cargo/bin
              end

        - name: Configure fish shell
          become: false
          ansible.builtin.blockinfile:
            path: "/home/{{ ansible_user }}/.config/fish/config.fish"
            create: true
            mode: "0644"
            marker: "# {mark} FISH SHELL CONFIGURATION"
            block: |
              # Disable welcome message
              set -g fish_greeting ""

              # Initialize starship prompt
              starship init fish | source

              # Initialize zoxide with cd instead of z
              zoxide init fish --cmd cd | source

              # Clear screen function
              function cls
                  clear
              end

              # eza aliases - group directories first
              if type -q eza
                  alias ll="eza -l -g --icons --git --group-directories-first"
                  alias ls="eza --grid --color=auto --git --icons --group-directories-first"
                  alias lt="eza --tree --level=2 --icons --group-directories-first"
                  alias la="eza -la --icons --group-directories-first"
                  alias l="eza -l --icons --group-directories-first"
                  alias tree="eza --tree --icons --group-directories-first"
              end

              # bottom configuration and aliases
              if type -q btm
                  # Function to handle process monitoring commands
                  function process_monitor
                      btm $argv
                  end

                  # Create aliases that point to the function
                  alias top="process_monitor"
                  alias htop="process_monitor"
                  alias btm="process_monitor"
              end

# Starship prompt installation and configuration
- name: Configure Shell Prompt
  block:
    - name: Check current starship version
      ansible.builtin.command: starship --version
      register: starship_current_version
      changed_when: false
      failed_when: false

    - name: Install Starship
      when: starship_current_version.rc != 0
      block:
        - name: Download starship installer
          ansible.builtin.get_url:
            url: https://starship.rs/install.sh
            dest: /tmp/starship-install.sh
            mode: "0755"

        - name: Install Starship
          ansible.builtin.command: /tmp/starship-install.sh --yes
          args:
            creates: /usr/local/bin/starship

        - name: Clean up starship installer
          ansible.builtin.file:
            path: /tmp/starship-install.sh
            state: absent
